### ISSUE TITLE
how to log to console

### ISSUE THREAD

**Issue by palmerabollo** [telefonicaid/pylogops#5]
The example in the readme adds a file_handler. What should I do if I don't want to write anything to a file? (just write to stdout).

```python
import logging
import time
from pylogops.logger import JsonFormatter

file_handler = logging.FileHandler('/tmp/my_log.log', encoding='UTF-8')
file_handler.setFormatter(JsonFormatter(converter=time.localtime))
logging.basicConfig()
logger = logging.getLogger("my_logger")
logger.addHandler(file_handler)
logger.setLevel(logging.INFO)
logger.info("Msg")
```

I think that should be the first example in the README, otherwise it looks too complex.

**Comment by ealogar** [comment]
Just change logging.FileHandler by logging.StreamHandler()
